# Generated by Django 5.1.6 on 2025-02-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_rename_fname_user_name_remove_user_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='123456789', max_length=500),
        ),
    ]
